<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="0" failed="5" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-12T06:16:00Z" name="BDD Test Suite" finished-at="2022-05-12T06:16:11Z" duration-ms="10892">
    <groups>
      <group name="cucumber">
        <method signature="TestRunner.feature(io.cucumber.testng.PickleWrapper, io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.api.myRunner.TestRunner@19932c16]" name="feature" class="com.api.myRunner.TestRunner"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2022-05-12T06:16:00Z" name="CucumberTeckTask" finished-at="2022-05-12T06:16:11Z" duration-ms="10892">
      <class name="com.api.myRunner.TestRunner">
        <test-method is-config="true" signature="setUpClass()[pri:0, instance:com.api.myRunner.TestRunner@19932c16]" started-at="2022-05-12T06:16:00Z" name="setUpClass" finished-at="2022-05-12T06:16:01Z" duration-ms="315" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="feature(io.cucumber.testng.PickleWrapper, io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.api.myRunner.TestRunner@19932c16]" started-at="2022-05-12T06:16:01Z" name="feature" description="Runs Cucumber Feature" data-provider="features" finished-at="2022-05-12T06:16:05Z" duration-ms="3948" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["As a user,I can retrive Nace Details by using order details"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["As a user, I can verify the proper respose from API"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[398481Is not matching with io.restassured.path.xml.XmlPath@47c26664 expected [398481] but found [io.restassured.path.xml.XmlPath@7f74fefa]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 398481Is not matching with io.restassured.path.xml.XmlPath@47c26664 expected [398481] but found [io.restassured.path.xml.XmlPath@7f74fefa]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at stepDefinitions.GetNaceDetailsDefinition.verify_nace_details_are_as_per(GetNaceDetailsDefinition.java:59)
at ✽.verify NaceDetails are as per "398481"(file:///C:/Users/prash/LUXOFTTESTNG/CucumberTechTask/src/main/java/Features/getNaceDetails.feature:8)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method signature="feature(io.cucumber.testng.PickleWrapper, io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.api.myRunner.TestRunner@19932c16]" started-at="2022-05-12T06:16:05Z" name="feature" description="Runs Cucumber Feature" data-provider="features" finished-at="2022-05-12T06:16:06Z" duration-ms="1525" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["As a user,I can retrive Nace Details by using order details"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["As a user, I can verify the proper respose from API"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[398482Is not matching with io.restassured.path.xml.XmlPath@440e3972 expected [398482] but found [io.restassured.path.xml.XmlPath@ef77972]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 398482Is not matching with io.restassured.path.xml.XmlPath@440e3972 expected [398482] but found [io.restassured.path.xml.XmlPath@ef77972]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at stepDefinitions.GetNaceDetailsDefinition.verify_nace_details_are_as_per(GetNaceDetailsDefinition.java:59)
at ✽.verify NaceDetails are as per "398482"(file:///C:/Users/prash/LUXOFTTESTNG/CucumberTechTask/src/main/java/Features/getNaceDetails.feature:8)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method signature="feature(io.cucumber.testng.PickleWrapper, io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.api.myRunner.TestRunner@19932c16]" started-at="2022-05-12T06:16:06Z" name="feature" description="Runs Cucumber Feature" data-provider="features" finished-at="2022-05-12T06:16:08Z" duration-ms="1434" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["As a user,I can retrive Nace Details by using order details"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["As a user, I can verify the proper respose from API"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[398483Is not matching with io.restassured.path.xml.XmlPath@489fa87e expected [398483] but found [io.restassured.path.xml.XmlPath@19048fda]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 398483Is not matching with io.restassured.path.xml.XmlPath@489fa87e expected [398483] but found [io.restassured.path.xml.XmlPath@19048fda]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at stepDefinitions.GetNaceDetailsDefinition.verify_nace_details_are_as_per(GetNaceDetailsDefinition.java:59)
at ✽.verify NaceDetails are as per "398483"(file:///C:/Users/prash/LUXOFTTESTNG/CucumberTechTask/src/main/java/Features/getNaceDetails.feature:8)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method signature="feature(io.cucumber.testng.PickleWrapper, io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.api.myRunner.TestRunner@19932c16]" started-at="2022-05-12T06:16:08Z" name="feature" description="Runs Cucumber Feature" data-provider="features" finished-at="2022-05-12T06:16:09Z" duration-ms="1520" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["As a user,I can retrive Nace Details by using order details"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["As a user, I can verify the proper respose from API"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[398484Is not matching with io.restassured.path.xml.XmlPath@72f628d6 expected [398484] but found [io.restassured.path.xml.XmlPath@1e8d4d07]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 398484Is not matching with io.restassured.path.xml.XmlPath@72f628d6 expected [398484] but found [io.restassured.path.xml.XmlPath@1e8d4d07]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at stepDefinitions.GetNaceDetailsDefinition.verify_nace_details_are_as_per(GetNaceDetailsDefinition.java:59)
at ✽.verify NaceDetails are as per "398484"(file:///C:/Users/prash/LUXOFTTESTNG/CucumberTechTask/src/main/java/Features/getNaceDetails.feature:8)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method signature="feature(io.cucumber.testng.PickleWrapper, io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.api.myRunner.TestRunner@19932c16]" started-at="2022-05-12T06:16:09Z" name="feature" description="Runs Cucumber Feature" data-provider="features" finished-at="2022-05-12T06:16:11Z" duration-ms="1403" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["As a user,I can retrive Nace Details by using order details"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["As a user, I can verify the proper respose from API"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[398485Is not matching with io.restassured.path.xml.XmlPath@697913e6 expected [398485] but found [io.restassured.path.xml.XmlPath@58a60d56]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 398485Is not matching with io.restassured.path.xml.XmlPath@697913e6 expected [398485] but found [io.restassured.path.xml.XmlPath@58a60d56]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at stepDefinitions.GetNaceDetailsDefinition.verify_nace_details_are_as_per(GetNaceDetailsDefinition.java:59)
at ✽.verify NaceDetails are as per "398485"(file:///C:/Users/prash/LUXOFTTESTNG/CucumberTechTask/src/main/java/Features/getNaceDetails.feature:8)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:com.api.myRunner.TestRunner@19932c16]" started-at="2022-05-12T06:16:11Z" name="tearDownClass" finished-at="2022-05-12T06:16:11Z" duration-ms="718" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- com.api.myRunner.TestRunner -->
    </test> <!-- CucumberTeckTask -->
  </suite> <!-- BDD Test Suite -->
</testng-results>
